// ======================================================================
// TROUVAILLE WIDGET & CARD CUSTOMIZATION ENGINE TYPES
// iOS-Style Springboard Widget Hierarchy & Sizing
// Strictly compliant with GEMINI.md: Monochrome Apple Luxury Theme
// ======================================================================

export type WidgetSize = "full" | "half" | "expanded";

export interface CardWidgetConfig {
  id: string;
  title: string;
  subtitle: string;
  page: "home" | "statistics";
  category: "portfolio" | "telemetry" | "ledger" | "planning" | "social";
  size: WidgetSize;
  supportedSizes: WidgetSize[];
  order: number;
  isVisible: boolean;
}

export const DEFAULT_HOME_WIDGETS: CardWidgetConfig[] = [
  {
    id: "net_portfolio",
    title: "Net Portfolio",
    subtitle: "Total wealth & asset valuation",
    page: "home",
    category: "portfolio",
    size: "full",
    supportedSizes: ["full"],
    order: 0,
    isVisible: true,
  },
  {
    id: "portfolio_account",
    title: "Portfolio Accounts",
    subtitle: "Account cards & liquid balances",
    page: "home",
    category: "portfolio",
    size: "full",
    supportedSizes: ["full"],
    order: 1,
    isVisible: true,
  },
  {
    id: "spending_stability",
    title: "Spending Stability",
    subtitle: "Daily variance & consistency telemetry",
    page: "home",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 2,
    isVisible: true,
  },
  {
    id: "cashflow_pulse",
    title: "Cashflow Pulse & Budget",
    subtitle: "Monthly income, expenses & spending pacing",
    page: "home",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 3,
    isVisible: true,
  },
  {
    id: "ai_insights",
    title: "AI Financial Insights",
    subtitle: "Smart diagnostics & anomalous alerts",
    page: "home",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 4,
    isVisible: true,
  },
  {
    id: "activity_heatmap",
    title: "Activity Heatmap",
    subtitle: "Daily transaction density & frequency",
    page: "home",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full"],
    order: 5,
    isVisible: true,
  },
  {
    id: "financial_goals",
    title: "Financial Goals",
    subtitle: "Savings targets & milestone achievement",
    page: "home",
    category: "planning",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 6,
    isVisible: true,
  },
  {
    id: "upcoming_bills",
    title: "Upcoming Bills",
    subtitle: "Subscriptions & recurring bill schedule",
    page: "home",
    category: "planning",
    size: "full",
    supportedSizes: ["full"],
    order: 7,
    isVisible: true,
  },
  {
    id: "recent_transactions",
    title: "Recent Transactions",
    subtitle: "Quick ledger feed of latest activity",
    page: "home",
    category: "ledger",
    size: "full",
    supportedSizes: ["full"],
    order: 8,
    isVisible: true,
  },
  {
    id: "top_categories",
    title: "Top Spending Categories",
    subtitle: "Monthly breakdown of largest drivers",
    page: "home",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 9,
    isVisible: true,
  },
  {
    id: "savings_rate_velocity",
    title: "Savings Rate & Velocity",
    subtitle: "Net capital retention & daily runway",
    page: "home",
    category: "planning",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 10,
    isVisible: true,
  },
  {
    id: "split_bill",
    title: "Split Bill & Receivables",
    subtitle: "Friend shares & pending settlements",
    page: "home",
    category: "social",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 11,
    isVisible: true,
  },
  {
    id: "savings_ring",
    title: "Savings Rate Ring",
    subtitle: "Circular capital retention progress",
    page: "home",
    category: "planning",
    size: "half",
    supportedSizes: ["full", "half"],
    order: 12,
    isVisible: true,
  },
  {
    id: "spending_velocity_bar",
    title: "7-Day Velocity Bar",
    subtitle: "Daily outflow pace vs safe allowance",
    page: "home",
    category: "telemetry",
    size: "half",
    supportedSizes: ["full", "half"],
    order: 13,
    isVisible: true,
  },
  {
    id: "category_donut",
    title: "Category Donut Chart",
    subtitle: "Top expense allocation distribution",
    page: "home",
    category: "telemetry",
    size: "half",
    supportedSizes: ["full", "half"],
    order: 14,
    isVisible: true,
  },
  {
    id: "mini_heatmap",
    title: "Activity Dot Heatmap",
    subtitle: "28-day transaction density matrix",
    page: "home",
    category: "telemetry",
    size: "half",
    supportedSizes: ["full", "half"],
    order: 15,
    isVisible: true,
  },
  {
    id: "financial_health_gauge",
    title: "Executive Health Meter",
    subtitle: "Financial health score & grade gauge",
    page: "home",
    category: "telemetry",
    size: "half",
    supportedSizes: ["full", "half"],
    order: 16,
    isVisible: true,
  },
  {
    id: "liquid_runway",
    title: "Liquid Buffer Runway",
    subtitle: "Emergency reserve runway & liquid ratio",
    page: "home",
    category: "planning",
    size: "half",
    supportedSizes: ["full", "half"],
    order: 17,
    isVisible: true,
  },
];

export type HomePresetKey =
  | "minimal"
  | "pulse"
  | "horizon"
  | "executive"
  | "simple"
  | "balanced"
  | "advanced";

export interface HomePresetDefinition {
  key: HomePresetKey;
  label: string;
  description: string;
  cardConfigs: { id: string; size: WidgetSize; isVisible: boolean; order: number }[];
}

export const HOME_PRESETS: HomePresetDefinition[] = [
  {
    key: "minimal",
    label: "Minimal",
    description: "Distraction-free balances, cashflow & upcoming bills",
    cardConfigs: [
      { id: "net_portfolio", size: "full", isVisible: true, order: 0 },
      { id: "portfolio_account", size: "full", isVisible: true, order: 1 },
      { id: "cashflow_pulse", size: "full", isVisible: true, order: 2 },
      { id: "upcoming_bills", size: "full", isVisible: true, order: 3 },
      { id: "recent_transactions", size: "full", isVisible: true, order: 4 },
      { id: "savings_ring", size: "half", isVisible: false, order: 5 },
      { id: "spending_velocity_bar", size: "half", isVisible: false, order: 6 },
      { id: "category_donut", size: "half", isVisible: false, order: 7 },
      { id: "mini_heatmap", size: "half", isVisible: false, order: 8 },
      { id: "financial_health_gauge", size: "half", isVisible: false, order: 9 },
      { id: "liquid_runway", size: "half", isVisible: false, order: 10 },
      { id: "spending_stability", size: "full", isVisible: false, order: 11 },
      { id: "ai_insights", size: "full", isVisible: false, order: 12 },
      { id: "activity_heatmap", size: "full", isVisible: false, order: 13 },
      { id: "financial_goals", size: "full", isVisible: false, order: 14 },
      { id: "top_categories", size: "full", isVisible: false, order: 15 },
      { id: "savings_rate_velocity", size: "full", isVisible: false, order: 16 },
      { id: "split_bill", size: "full", isVisible: false, order: 17 },
    ],
  },
  {
    key: "pulse",
    label: "Pulse",
    description: "Daily spending velocity, category donut & operational cadence",
    cardConfigs: [
      { id: "net_portfolio", size: "full", isVisible: true, order: 0 },
      { id: "portfolio_account", size: "full", isVisible: true, order: 1 },
      { id: "spending_velocity_bar", size: "half", isVisible: true, order: 2 },
      { id: "category_donut", size: "half", isVisible: true, order: 3 },
      { id: "cashflow_pulse", size: "full", isVisible: true, order: 4 },
      { id: "mini_heatmap", size: "half", isVisible: true, order: 5 },
      { id: "spending_stability", size: "half", isVisible: true, order: 6 },
      { id: "recent_transactions", size: "full", isVisible: true, order: 7 },
      { id: "upcoming_bills", size: "full", isVisible: true, order: 8 },
      { id: "savings_ring", size: "half", isVisible: false, order: 9 },
      { id: "financial_health_gauge", size: "half", isVisible: false, order: 10 },
      { id: "liquid_runway", size: "half", isVisible: false, order: 11 },
      { id: "ai_insights", size: "full", isVisible: false, order: 12 },
      { id: "activity_heatmap", size: "full", isVisible: false, order: 13 },
      { id: "financial_goals", size: "full", isVisible: false, order: 14 },
      { id: "top_categories", size: "full", isVisible: false, order: 15 },
      { id: "savings_rate_velocity", size: "full", isVisible: false, order: 16 },
      { id: "split_bill", size: "full", isVisible: false, order: 17 },
    ],
  },
  {
    key: "horizon",
    label: "Horizon",
    description: "Long-term wealth retention, emergency buffer & savings targets",
    cardConfigs: [
      { id: "net_portfolio", size: "full", isVisible: true, order: 0 },
      { id: "portfolio_account", size: "full", isVisible: true, order: 1 },
      { id: "savings_ring", size: "half", isVisible: true, order: 2 },
      { id: "liquid_runway", size: "half", isVisible: true, order: 3 },
      { id: "financial_health_gauge", size: "half", isVisible: true, order: 4 },
      { id: "financial_goals", size: "half", isVisible: true, order: 5 },
      { id: "cashflow_pulse", size: "full", isVisible: true, order: 6 },
      { id: "upcoming_bills", size: "full", isVisible: true, order: 7 },
      { id: "savings_rate_velocity", size: "full", isVisible: true, order: 8 },
      { id: "recent_transactions", size: "full", isVisible: false, order: 9 },
      { id: "spending_velocity_bar", size: "half", isVisible: false, order: 10 },
      { id: "category_donut", size: "half", isVisible: false, order: 11 },
      { id: "mini_heatmap", size: "half", isVisible: false, order: 12 },
      { id: "spending_stability", size: "full", isVisible: false, order: 13 },
      { id: "ai_insights", size: "full", isVisible: false, order: 14 },
      { id: "activity_heatmap", size: "full", isVisible: false, order: 15 },
      { id: "top_categories", size: "full", isVisible: false, order: 16 },
      { id: "split_bill", size: "full", isVisible: false, order: 17 },
    ],
  },
  {
    key: "executive",
    label: "Executive",
    description: "Complete power telemetry with paired visual micro-widgets",
    cardConfigs: [
      { id: "net_portfolio", size: "full", isVisible: true, order: 0 },
      { id: "portfolio_account", size: "full", isVisible: true, order: 1 },
      { id: "savings_ring", size: "half", isVisible: true, order: 2 },
      { id: "spending_velocity_bar", size: "half", isVisible: true, order: 3 },
      { id: "category_donut", size: "half", isVisible: true, order: 4 },
      { id: "mini_heatmap", size: "half", isVisible: true, order: 5 },
      { id: "financial_health_gauge", size: "half", isVisible: true, order: 6 },
      { id: "liquid_runway", size: "half", isVisible: true, order: 7 },
      { id: "cashflow_pulse", size: "full", isVisible: true, order: 8 },
      { id: "upcoming_bills", size: "half", isVisible: true, order: 9 },
      { id: "financial_goals", size: "half", isVisible: true, order: 10 },
      { id: "spending_stability", size: "full", isVisible: true, order: 11 },
      { id: "ai_insights", size: "full", isVisible: true, order: 12 },
      { id: "recent_transactions", size: "full", isVisible: true, order: 13 },
      { id: "split_bill", size: "half", isVisible: false, order: 14 },
      { id: "top_categories", size: "half", isVisible: false, order: 15 },
      { id: "activity_heatmap", size: "full", isVisible: false, order: 16 },
      { id: "savings_rate_velocity", size: "full", isVisible: false, order: 17 },
    ],
  },
];

export const DEFAULT_STATISTICS_WIDGETS: CardWidgetConfig[] = [
  {
    id: "health_score",
    title: "Financial Health Score",
    subtitle: "Score, health metrics & performance rating",
    page: "statistics",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full"],
    order: 0,
    isVisible: true,
  },
  {
    id: "monte_carlo",
    title: "Monte Carlo Simulator",
    subtitle: "Stochastic wealth dispersion & projection",
    page: "statistics",
    category: "planning",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 1,
    isVisible: true,
  },
  {
    id: "fire_planner",
    title: "FIRE Independence Planner",
    subtitle: "Retirement velocity & target capital runway",
    page: "statistics",
    category: "planning",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 2,
    isVisible: true,
  },
  {
    id: "cashflow_outlook",
    title: "Cashflow Outlook",
    subtitle: "Income vs expense pacing & forecast floor",
    page: "statistics",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 3,
    isVisible: true,
  },
  {
    id: "liquidity_horizon",
    title: "Liquidity Horizon",
    subtitle: "Liquid runway & reserve safety buffer",
    page: "statistics",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 4,
    isVisible: true,
  },
  {
    id: "zero_based_envelopes",
    title: "Zero-Based Envelopes",
    subtitle: "Monthly capital allocation across envelopes",
    page: "statistics",
    category: "planning",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 5,
    isVisible: true,
  },
  {
    id: "spending_patterns",
    title: "Spending Patterns",
    subtitle: "Temporal trends & behavioral spending shifts",
    page: "statistics",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full"],
    order: 6,
    isVisible: true,
  },
  {
    id: "spending_density_heatmap",
    title: "Spending Density Heatmap",
    subtitle: "Daily transaction cluster & calendar density",
    page: "statistics",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full"],
    order: 7,
    isVisible: true,
  },
  {
    id: "debt_payoff",
    title: "Debt Payoff Engine",
    subtitle: "Snowball vs Avalanche payoff acceleration",
    page: "statistics",
    category: "planning",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 8,
    isVisible: true,
  },
  {
    id: "what_if_simulator",
    title: "What-If Simulator",
    subtitle: "Income/expense shock scenario modeling",
    page: "statistics",
    category: "planning",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 9,
    isVisible: true,
  },
  {
    id: "personal_financial_model",
    title: "Personal Financial Model",
    subtitle: "Structural actual vs baseline financial trajectory",
    page: "statistics",
    category: "planning",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 10,
    isVisible: true,
  },
];
