// ======================================================================
// TROUVAILLE WIDGET & CARD CUSTOMIZATION ENGINE TYPES
// iOS-Style Springboard Widget Hierarchy & Sizing
// Strictly compliant with GEMINI.md: Monochrome Apple Luxury Theme
// ======================================================================

export type WidgetSize = "full" | "half" | "expanded";

export interface CardWidgetConfig {
  id: string;
  title: string;
  subtitle: string;
  page: "home" | "statistics";
  category: "portfolio" | "telemetry" | "ledger" | "planning" | "social";
  size: WidgetSize;
  supportedSizes: WidgetSize[];
  order: number;
  isVisible: boolean;
}

export const DEFAULT_HOME_WIDGETS: CardWidgetConfig[] = [
  {
    id: "net_portfolio",
    title: "Net Portfolio",
    subtitle: "Total wealth & asset valuation",
    page: "home",
    category: "portfolio",
    size: "full",
    supportedSizes: ["full"],
    order: 0,
    isVisible: true,
  },
  {
    id: "portfolio_account",
    title: "Portfolio Accounts",
    subtitle: "Account cards & liquid balances",
    page: "home",
    category: "portfolio",
    size: "full",
    supportedSizes: ["full"],
    order: 1,
    isVisible: true,
  },
  {
    id: "spending_stability",
    title: "Spending Stability",
    subtitle: "Daily variance & consistency telemetry",
    page: "home",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 2,
    isVisible: true,
  },
  {
    id: "cashflow_pulse",
    title: "Cashflow Pulse & Budget",
    subtitle: "Monthly income, expenses & spending pacing",
    page: "home",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 3,
    isVisible: true,
  },
  {
    id: "ai_insights",
    title: "AI Financial Insights",
    subtitle: "Smart diagnostics & anomalous alerts",
    page: "home",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 4,
    isVisible: true,
  },
  {
    id: "activity_heatmap",
    title: "Activity Heatmap",
    subtitle: "Daily transaction density & frequency",
    page: "home",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full"],
    order: 5,
    isVisible: true,
  },
  {
    id: "financial_goals",
    title: "Financial Goals",
    subtitle: "Savings targets & milestone achievement",
    page: "home",
    category: "planning",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 6,
    isVisible: true,
  },
  {
    id: "upcoming_bills",
    title: "Upcoming Bills",
    subtitle: "Subscriptions & recurring bill schedule",
    page: "home",
    category: "planning",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 7,
    isVisible: true,
  },
  {
    id: "recent_transactions",
    title: "Recent Transactions",
    subtitle: "Quick ledger feed of latest activity",
    page: "home",
    category: "ledger",
    size: "full",
    supportedSizes: ["full"],
    order: 8,
    isVisible: true,
  },
  {
    id: "top_categories",
    title: "Top Spending Categories",
    subtitle: "Monthly breakdown of largest drivers",
    page: "home",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 9,
    isVisible: true,
  },
  {
    id: "savings_rate_velocity",
    title: "Savings Rate & Velocity",
    subtitle: "Net capital retention & daily runway",
    page: "home",
    category: "planning",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 10,
    isVisible: true,
  },
  {
    id: "split_bill",
    title: "Split Bill & Receivables",
    subtitle: "Friend shares & pending settlements",
    page: "home",
    category: "social",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 11,
    isVisible: true,
  },
  {
    id: "savings_ring",
    title: "Savings Rate Ring",
    subtitle: "Circular capital retention progress",
    page: "home",
    category: "planning",
    size: "half",
    supportedSizes: ["full", "half"],
    order: 12,
    isVisible: true,
  },
  {
    id: "spending_velocity_bar",
    title: "7-Day Velocity Bar",
    subtitle: "Daily outflow pace vs safe allowance",
    page: "home",
    category: "telemetry",
    size: "half",
    supportedSizes: ["full", "half"],
    order: 13,
    isVisible: true,
  },
  {
    id: "category_donut",
    title: "Category Donut Chart",
    subtitle: "Top expense allocation distribution",
    page: "home",
    category: "telemetry",
    size: "half",
    supportedSizes: ["full", "half"],
    order: 14,
    isVisible: true,
  },
  {
    id: "mini_heatmap",
    title: "Activity Dot Heatmap",
    subtitle: "28-day transaction density matrix",
    page: "home",
    category: "telemetry",
    size: "half",
    supportedSizes: ["full", "half"],
    order: 15,
    isVisible: true,
  },
  {
    id: "financial_health_gauge",
    title: "Executive Health Meter",
    subtitle: "Financial health score & grade gauge",
    page: "home",
    category: "telemetry",
    size: "half",
    supportedSizes: ["full", "half"],
    order: 16,
    isVisible: true,
  },
  {
    id: "calendar_activity",
    title: "Calendar Activity",
    subtitle: "Daily transaction schedule & monthly entries",
    page: "home",
    category: "planning",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 2,
    isVisible: true,
  },
  {
    id: "liquid_runway",
    title: "Cashflow Runway",
    subtitle: "Survival buffer & emergency reserve runway",
    page: "home",
    category: "planning",
    size: "half",
    supportedSizes: ["full", "half"],
    order: 18,
    isVisible: true,
  },
];

export type HomePresetKey =
  | "minimal"
  | "pulse"
  | "horizon"
  | "executive"
  | "simple"
  | "balanced"
  | "advanced";

export interface HomePresetDefinition {
  key: HomePresetKey;
  label: string;
  description: string;
  cardConfigs: { id: string; size: WidgetSize; isVisible: boolean; order: number }[];
}

export const HOME_PRESETS: HomePresetDefinition[] = [
  {
    key: "minimal",
    label: "Minimal",
    description: "Distraction-free balances, cashflow & upcoming bills",
    cardConfigs: [
      { id: "net_portfolio", size: "full", isVisible: true, order: 0 },
      { id: "portfolio_account", size: "full", isVisible: true, order: 1 },
      { id: "calendar_activity", size: "full", isVisible: true, order: 2 },
      { id: "cashflow_pulse", size: "full", isVisible: true, order: 3 },
      { id: "upcoming_bills", size: "full", isVisible: true, order: 4 },
      { id: "recent_transactions", size: "full", isVisible: true, order: 5 },
      { id: "savings_ring", size: "half", isVisible: false, order: 6 },
      { id: "spending_velocity_bar", size: "half", isVisible: false, order: 7 },
      { id: "category_donut", size: "half", isVisible: false, order: 8 },
      { id: "mini_heatmap", size: "half", isVisible: false, order: 9 },
      { id: "financial_health_gauge", size: "half", isVisible: false, order: 10 },
      { id: "liquid_runway", size: "half", isVisible: false, order: 11 },
      { id: "spending_stability", size: "full", isVisible: false, order: 12 },
      { id: "ai_insights", size: "full", isVisible: false, order: 13 },
      { id: "activity_heatmap", size: "full", isVisible: false, order: 14 },
      { id: "financial_goals", size: "full", isVisible: false, order: 15 },
      { id: "top_categories", size: "full", isVisible: false, order: 16 },
      { id: "savings_rate_velocity", size: "full", isVisible: false, order: 17 },
      { id: "split_bill", size: "full", isVisible: false, order: 18 },
    ],
  },
  {
    key: "pulse",
    label: "Balanced",
    description: "Daily spending velocity, category allocation & activity",
    cardConfigs: [
      { id: "net_portfolio", size: "full", isVisible: true, order: 0 },
      { id: "portfolio_account", size: "full", isVisible: true, order: 1 },
      { id: "calendar_activity", size: "full", isVisible: true, order: 2 },
      { id: "spending_velocity_bar", size: "half", isVisible: true, order: 3 },
      { id: "category_donut", size: "half", isVisible: true, order: 4 },
      { id: "cashflow_pulse", size: "full", isVisible: true, order: 5 },
      { id: "savings_ring", size: "half", isVisible: true, order: 6 },
      { id: "mini_heatmap", size: "half", isVisible: true, order: 7 },
      { id: "upcoming_bills", size: "full", isVisible: true, order: 8 },
      { id: "recent_transactions", size: "full", isVisible: true, order: 9 },
      { id: "financial_health_gauge", size: "half", isVisible: false, order: 10 },
      { id: "liquid_runway", size: "half", isVisible: false, order: 11 },
      { id: "spending_stability", size: "full", isVisible: false, order: 12 },
      { id: "ai_insights", size: "full", isVisible: false, order: 13 },
      { id: "activity_heatmap", size: "full", isVisible: false, order: 14 },
      { id: "financial_goals", size: "full", isVisible: false, order: 15 },
      { id: "top_categories", size: "full", isVisible: false, order: 16 },
      { id: "savings_rate_velocity", size: "full", isVisible: false, order: 17 },
      { id: "split_bill", size: "full", isVisible: false, order: 18 },
    ],
  },
  {
    key: "horizon",
    label: "Horizon",
    description: "Long-term wealth retention, emergency runway & goals",
    cardConfigs: [
      { id: "net_portfolio", size: "full", isVisible: true, order: 0 },
      { id: "portfolio_account", size: "full", isVisible: true, order: 1 },
      { id: "calendar_activity", size: "full", isVisible: true, order: 2 },
      { id: "liquid_runway", size: "half", isVisible: true, order: 3 },
      { id: "financial_health_gauge", size: "half", isVisible: true, order: 4 },
      { id: "savings_ring", size: "half", isVisible: true, order: 5 },
      { id: "mini_heatmap", size: "half", isVisible: true, order: 6 },
      { id: "cashflow_pulse", size: "full", isVisible: true, order: 7 },
      { id: "spending_stability", size: "full", isVisible: true, order: 8 },
      { id: "upcoming_bills", size: "full", isVisible: true, order: 9 },
      { id: "financial_goals", size: "full", isVisible: true, order: 10 },
      { id: "recent_transactions", size: "full", isVisible: true, order: 11 },
      { id: "spending_velocity_bar", size: "half", isVisible: false, order: 12 },
      { id: "category_donut", size: "half", isVisible: false, order: 13 },
      { id: "savings_rate_velocity", size: "full", isVisible: false, order: 14 },
      { id: "ai_insights", size: "full", isVisible: false, order: 15 },
      { id: "activity_heatmap", size: "full", isVisible: false, order: 16 },
      { id: "top_categories", size: "full", isVisible: false, order: 17 },
      { id: "split_bill", size: "full", isVisible: false, order: 18 },
    ],
  },
  {
    key: "executive",
    label: "Executive",
    description: "Complete command center with paired visual micro-widgets",
    cardConfigs: [
      { id: "net_portfolio", size: "full", isVisible: true, order: 0 },
      { id: "portfolio_account", size: "full", isVisible: true, order: 1 },
      { id: "calendar_activity", size: "full", isVisible: true, order: 2 },
      { id: "spending_velocity_bar", size: "half", isVisible: true, order: 3 },
      { id: "savings_ring", size: "half", isVisible: true, order: 4 },
      { id: "category_donut", size: "half", isVisible: true, order: 5 },
      { id: "mini_heatmap", size: "half", isVisible: true, order: 6 },
      { id: "liquid_runway", size: "half", isVisible: true, order: 7 },
      { id: "financial_health_gauge", size: "half", isVisible: true, order: 8 },
      { id: "cashflow_pulse", size: "full", isVisible: true, order: 9 },
      { id: "spending_stability", size: "full", isVisible: true, order: 10 },
      { id: "ai_insights", size: "full", isVisible: true, order: 11 },
      { id: "upcoming_bills", size: "full", isVisible: true, order: 12 },
      { id: "financial_goals", size: "full", isVisible: true, order: 13 },
      { id: "recent_transactions", size: "full", isVisible: true, order: 14 },
      { id: "split_bill", size: "half", isVisible: false, order: 15 },
      { id: "top_categories", size: "half", isVisible: false, order: 16 },
      { id: "activity_heatmap", size: "full", isVisible: false, order: 17 },
      { id: "savings_rate_velocity", size: "full", isVisible: false, order: 18 },
    ],
  },
];

export const DEFAULT_STATISTICS_WIDGETS: CardWidgetConfig[] = [
  // --- INTELLIGENCE CARDS ---
  {
    id: "health_score",
    title: "Financial Health Score",
    subtitle: "Score, health metrics & performance rating",
    page: "statistics",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full"],
    order: 0,
    isVisible: true,
  },
  {
    id: "cashflow_outlook",
    title: "Cashflow Outlook",
    subtitle: "Income vs expense pacing & forecast floor",
    page: "statistics",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full"],
    order: 1,
    isVisible: true,
  },
  {
    id: "liquidity_horizon",
    title: "Liquidity Horizon",
    subtitle: "Liquid runway & reserve safety buffer",
    page: "statistics",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full"],
    order: 2,
    isVisible: true,
  },
  {
    id: "monte_carlo",
    title: "Monte Carlo Simulator",
    subtitle: "Stochastic wealth dispersion & projection",
    page: "statistics",
    category: "planning",
    size: "full",
    supportedSizes: ["full"],
    order: 3,
    isVisible: true,
  },
  {
    id: "fire_planner",
    title: "FIRE Independence Planner",
    subtitle: "Retirement velocity & target capital runway",
    page: "statistics",
    category: "planning",
    size: "full",
    supportedSizes: ["full"],
    order: 4,
    isVisible: true,
  },
  {
    id: "spending_patterns",
    title: "Spending Patterns",
    subtitle: "Temporal trends & behavioral spending shifts",
    page: "statistics",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full"],
    order: 5,
    isVisible: true,
  },
  {
    id: "spending_density_heatmap",
    title: "Spending Density Heatmap",
    subtitle: "Daily transaction cluster & calendar density",
    page: "statistics",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full"],
    order: 6,
    isVisible: true,
  },
  {
    id: "zero_based_envelopes",
    title: "Zero-Based Envelopes",
    subtitle: "Monthly capital allocation across envelopes",
    page: "statistics",
    category: "planning",
    size: "full",
    supportedSizes: ["full"],
    order: 7,
    isVisible: true,
  },
  {
    id: "debt_payoff",
    title: "Debt Payoff Engine",
    subtitle: "Snowball vs Avalanche payoff acceleration",
    page: "statistics",
    category: "planning",
    size: "full",
    supportedSizes: ["full"],
    order: 8,
    isVisible: true,
  },
  {
    id: "what_if_simulator",
    title: "What-If Simulator",
    subtitle: "Income/expense shock scenario modeling",
    page: "statistics",
    category: "planning",
    size: "full",
    supportedSizes: ["full"],
    order: 9,
    isVisible: true,
  },
  {
    id: "personal_financial_model",
    title: "Personal Financial Model",
    subtitle: "Structural actual vs baseline financial trajectory",
    page: "statistics",
    category: "planning",
    size: "full",
    supportedSizes: ["full"],
    order: 10,
    isVisible: true,
  },

  // --- REPORT TAB SECTIONS ---
  {
    id: "financial_report",
    title: "Financial Report & Breakdown",
    subtitle: "Category expense/income distribution and trend",
    page: "statistics",
    category: "ledger",
    size: "full",
    supportedSizes: ["full"],
    order: 11,
    isVisible: true,
  },
  {
    id: "monthly_review",
    title: "Monthly Financial Review",
    subtitle: "Income vs expense performance and top shifts",
    page: "statistics",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full"],
    order: 12,
    isVisible: true,
  },
  {
    id: "personal_baseline",
    title: "Personal Spending Baseline",
    subtitle: "Fixed vs discretionary baseline tracking",
    page: "statistics",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full"],
    order: 13,
    isVisible: true,
  },
  {
    id: "expense_structure",
    title: "Expense Structure Analysis",
    subtitle: "Structural breakdown of monthly commitments",
    page: "statistics",
    category: "planning",
    size: "full",
    supportedSizes: ["full"],
    order: 14,
    isVisible: true,
  },

  // --- CASHFLOW & ASSETS SECTIONS ---
  {
    id: "cashflow_summary",
    title: "Period Cashflow Summary",
    subtitle: "Operating, financing and net cashflow summary",
    page: "statistics",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full"],
    order: 15,
    isVisible: true,
  },
  {
    id: "category_breakdown",
    title: "Category Breakdown",
    subtitle: "Outflow & inflow distribution by category",
    page: "statistics",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full"],
    order: 16,
    isVisible: true,
  },
  {
    id: "cashflow_sankey",
    title: "Cashflow Sankey Distribution",
    subtitle: "Visual flow from income sources into destinations",
    page: "statistics",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full"],
    order: 17,
    isVisible: true,
  },
  {
    id: "net_capital_trajectory",
    title: "Net Capital Trajectory",
    subtitle: "Cumulative net worth change over time",
    page: "statistics",
    category: "portfolio",
    size: "full",
    supportedSizes: ["full"],
    order: 18,
    isVisible: true,
  },
  {
    id: "inflow_outflow_trend",
    title: "Inflow vs Outflow Trend",
    subtitle: "Historical income vs expense comparison",
    page: "statistics",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full"],
    order: 19,
    isVisible: true,
  },
  {
    id: "cashflow_velocity",
    title: "Cashflow Velocity & Pacing",
    subtitle: "Daily spending density and moving averages",
    page: "statistics",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full"],
    order: 20,
    isVisible: true,
  },
  {
    id: "asset_analytics",
    title: "Asset & Net Worth Analytics",
    subtitle: "Capital allocation and net worth growth trajectory",
    page: "statistics",
    category: "portfolio",
    size: "full",
    supportedSizes: ["full"],
    order: 21,
    isVisible: true,
  },
];

export type StatisticsPresetKey =
  | "executive"
  | "telemetry"
  | "planning"
  | "essential";

export interface StatisticsPresetDefinition {
  key: StatisticsPresetKey;
  label: string;
  description: string;
  cardConfigs: { id: string; size: WidgetSize; isVisible: boolean; order: number }[];
}

export const STATISTICS_PRESETS: StatisticsPresetDefinition[] = [
  {
    key: "executive",
    label: "Executive",
    description: "Complete command center: health score, wealth projection & scenario modeling",
    cardConfigs: [
      { id: "health_score", size: "full", isVisible: true, order: 0 },
      { id: "cashflow_outlook", size: "full", isVisible: true, order: 1 },
      { id: "liquidity_horizon", size: "full", isVisible: true, order: 2 },
      { id: "monte_carlo", size: "full", isVisible: true, order: 3 },
      { id: "fire_planner", size: "full", isVisible: true, order: 4 },
      { id: "spending_patterns", size: "full", isVisible: true, order: 5 },
      { id: "personal_financial_model", size: "full", isVisible: true, order: 6 },
      { id: "what_if_simulator", size: "full", isVisible: true, order: 7 },
      { id: "zero_based_envelopes", size: "full", isVisible: false, order: 8 },
      { id: "debt_payoff", size: "full", isVisible: false, order: 9 },
      { id: "spending_density_heatmap", size: "full", isVisible: false, order: 10 },
      { id: "financial_report", size: "full", isVisible: true, order: 11 },
      { id: "monthly_review", size: "full", isVisible: true, order: 12 },
      { id: "personal_baseline", size: "full", isVisible: true, order: 13 },
      { id: "expense_structure", size: "full", isVisible: true, order: 14 },
      { id: "cashflow_summary", size: "full", isVisible: true, order: 15 },
      { id: "category_breakdown", size: "full", isVisible: true, order: 16 },
      { id: "cashflow_sankey", size: "full", isVisible: true, order: 17 },
      { id: "net_capital_trajectory", size: "full", isVisible: true, order: 18 },
      { id: "inflow_outflow_trend", size: "full", isVisible: true, order: 19 },
      { id: "cashflow_velocity", size: "full", isVisible: true, order: 20 },
      { id: "asset_analytics", size: "full", isVisible: true, order: 21 },
    ],
  },
  {
    key: "telemetry",
    label: "Telemetry",
    description: "Operational cashflow, cyclical spending trends & calendar density",
    cardConfigs: [
      { id: "health_score", size: "full", isVisible: true, order: 0 },
      { id: "cashflow_outlook", size: "full", isVisible: true, order: 1 },
      { id: "liquidity_horizon", size: "full", isVisible: true, order: 2 },
      { id: "spending_patterns", size: "full", isVisible: true, order: 3 },
      { id: "spending_density_heatmap", size: "full", isVisible: true, order: 4 },
      { id: "zero_based_envelopes", size: "full", isVisible: false, order: 5 },
      { id: "monte_carlo", size: "full", isVisible: false, order: 6 },
      { id: "fire_planner", size: "full", isVisible: false, order: 7 },
      { id: "debt_payoff", size: "full", isVisible: false, order: 8 },
      { id: "what_if_simulator", size: "full", isVisible: false, order: 9 },
      { id: "personal_financial_model", size: "full", isVisible: false, order: 10 },
      { id: "financial_report", size: "full", isVisible: true, order: 11 },
      { id: "monthly_review", size: "full", isVisible: false, order: 12 },
      { id: "personal_baseline", size: "full", isVisible: false, order: 13 },
      { id: "expense_structure", size: "full", isVisible: true, order: 14 },
      { id: "cashflow_summary", size: "full", isVisible: true, order: 15 },
      { id: "category_breakdown", size: "full", isVisible: true, order: 16 },
      { id: "cashflow_sankey", size: "full", isVisible: true, order: 17 },
      { id: "net_capital_trajectory", size: "full", isVisible: false, order: 18 },
      { id: "inflow_outflow_trend", size: "full", isVisible: true, order: 19 },
      { id: "cashflow_velocity", size: "full", isVisible: true, order: 20 },
      { id: "asset_analytics", size: "full", isVisible: true, order: 21 },
    ],
  },
  {
    key: "planning",
    label: "Planning",
    description: "Long-term wealth accumulation, FIRE retirement & debt acceleration",
    cardConfigs: [
      { id: "fire_planner", size: "full", isVisible: true, order: 0 },
      { id: "monte_carlo", size: "full", isVisible: true, order: 1 },
      { id: "personal_financial_model", size: "full", isVisible: true, order: 2 },
      { id: "what_if_simulator", size: "full", isVisible: true, order: 3 },
      { id: "debt_payoff", size: "full", isVisible: true, order: 4 },
      { id: "zero_based_envelopes", size: "full", isVisible: true, order: 5 },
      { id: "liquidity_horizon", size: "full", isVisible: true, order: 6 },
      { id: "health_score", size: "full", isVisible: false, order: 7 },
      { id: "cashflow_outlook", size: "full", isVisible: false, order: 8 },
      { id: "spending_patterns", size: "full", isVisible: false, order: 9 },
      { id: "spending_density_heatmap", size: "full", isVisible: false, order: 10 },
      { id: "financial_report", size: "full", isVisible: false, order: 11 },
      { id: "monthly_review", size: "full", isVisible: true, order: 12 },
      { id: "personal_baseline", size: "full", isVisible: true, order: 13 },
      { id: "expense_structure", size: "full", isVisible: false, order: 14 },
      { id: "cashflow_summary", size: "full", isVisible: true, order: 15 },
      { id: "category_breakdown", size: "full", isVisible: true, order: 16 },
      { id: "cashflow_sankey", size: "full", isVisible: false, order: 17 },
      { id: "net_capital_trajectory", size: "full", isVisible: true, order: 18 },
      { id: "inflow_outflow_trend", size: "full", isVisible: false, order: 19 },
      { id: "cashflow_velocity", size: "full", isVisible: false, order: 20 },
      { id: "asset_analytics", size: "full", isVisible: true, order: 21 },
    ],
  },
  {
    key: "essential",
    label: "Essential",
    description: "Distraction-free baseline: financial health score, report & key balances",
    cardConfigs: [
      { id: "health_score", size: "full", isVisible: true, order: 0 },
      { id: "cashflow_outlook", size: "full", isVisible: true, order: 1 },
      { id: "liquidity_horizon", size: "full", isVisible: true, order: 2 },
      { id: "monte_carlo", size: "full", isVisible: false, order: 3 },
      { id: "fire_planner", size: "full", isVisible: false, order: 4 },
      { id: "zero_based_envelopes", size: "full", isVisible: false, order: 5 },
      { id: "spending_patterns", size: "full", isVisible: false, order: 6 },
      { id: "spending_density_heatmap", size: "full", isVisible: false, order: 7 },
      { id: "debt_payoff", size: "full", isVisible: false, order: 8 },
      { id: "what_if_simulator", size: "full", isVisible: false, order: 9 },
      { id: "personal_financial_model", size: "full", isVisible: false, order: 10 },
      { id: "financial_report", size: "full", isVisible: true, order: 11 },
      { id: "monthly_review", size: "full", isVisible: false, order: 12 },
      { id: "personal_baseline", size: "full", isVisible: false, order: 13 },
      { id: "expense_structure", size: "full", isVisible: false, order: 14 },
      { id: "cashflow_summary", size: "full", isVisible: true, order: 15 },
      { id: "category_breakdown", size: "full", isVisible: false, order: 16 },
      { id: "cashflow_sankey", size: "full", isVisible: false, order: 17 },
      { id: "net_capital_trajectory", size: "full", isVisible: false, order: 18 },
      { id: "inflow_outflow_trend", size: "full", isVisible: false, order: 19 },
      { id: "cashflow_velocity", size: "full", isVisible: false, order: 20 },
      { id: "asset_analytics", size: "full", isVisible: true, order: 21 },
    ],
  },
];
