// ======================================================================
// TROUVAILLE WIDGET & CARD CUSTOMIZATION ENGINE TYPES
// iOS-Style Springboard Widget Hierarchy & Sizing
// Strictly compliant with GEMINI.md: Monochrome Apple Luxury Theme
// ======================================================================

export type WidgetSize = "full" | "half" | "expanded";

export interface CardWidgetConfig {
  id: string;
  title: string;
  subtitle: string;
  page: "home" | "statistics";
  category: "portfolio" | "telemetry" | "ledger" | "planning" | "social";
  size: WidgetSize;
  supportedSizes: WidgetSize[];
  order: number;
  isVisible: boolean;
}

export const DEFAULT_HOME_WIDGETS: CardWidgetConfig[] = [
  {
    id: "net_portfolio",
    title: "Net Portfolio",
    subtitle: "Total wealth & asset valuation",
    page: "home",
    category: "portfolio",
    size: "full",
    supportedSizes: ["full"],
    order: 0,
    isVisible: true,
  },
  {
    id: "portfolio_account",
    title: "Portfolio Accounts",
    subtitle: "Account cards & liquid balances",
    page: "home",
    category: "portfolio",
    size: "full",
    supportedSizes: ["full"],
    order: 1,
    isVisible: true,
  },
  {
    id: "spending_stability",
    title: "Spending Stability",
    subtitle: "Daily variance & consistency telemetry",
    page: "home",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 2,
    isVisible: true,
  },
  {
    id: "cashflow_pulse",
    title: "Cashflow Pulse & Budget",
    subtitle: "Monthly income, expenses & spending pacing",
    page: "home",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 3,
    isVisible: true,
  },
  {
    id: "ai_insights",
    title: "AI Financial Insights",
    subtitle: "Smart diagnostics & anomalous alerts",
    page: "home",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 4,
    isVisible: true,
  },
  {
    id: "activity_heatmap",
    title: "Activity Heatmap",
    subtitle: "Daily transaction density & frequency",
    page: "home",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full"],
    order: 5,
    isVisible: true,
  },
  {
    id: "financial_goals",
    title: "Financial Goals",
    subtitle: "Savings targets & milestone achievement",
    page: "home",
    category: "planning",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 6,
    isVisible: true,
  },
  {
    id: "upcoming_bills",
    title: "Upcoming Bills",
    subtitle: "Subscriptions & recurring bill schedule",
    page: "home",
    category: "planning",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 7,
    isVisible: true,
  },
  {
    id: "recent_transactions",
    title: "Recent Transactions",
    subtitle: "Quick ledger feed of latest activity",
    page: "home",
    category: "ledger",
    size: "full",
    supportedSizes: ["full"],
    order: 8,
    isVisible: true,
  },
  {
    id: "top_categories",
    title: "Top Spending Categories",
    subtitle: "Monthly breakdown of largest drivers",
    page: "home",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 9,
    isVisible: true,
  },
  {
    id: "savings_rate_velocity",
    title: "Savings Rate & Velocity",
    subtitle: "Net capital retention & daily runway",
    page: "home",
    category: "planning",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 10,
    isVisible: true,
  },
  {
    id: "split_bill",
    title: "Split Bill & Receivables",
    subtitle: "Friend shares & pending settlements",
    page: "home",
    category: "social",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 11,
    isVisible: true,
  },
];

export const DEFAULT_STATISTICS_WIDGETS: CardWidgetConfig[] = [
  {
    id: "health_score",
    title: "Financial Health Score",
    subtitle: "Score, health metrics & performance rating",
    page: "statistics",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full"],
    order: 0,
    isVisible: true,
  },
  {
    id: "monte_carlo",
    title: "Monte Carlo Simulator",
    subtitle: "Stochastic wealth dispersion & projection",
    page: "statistics",
    category: "planning",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 1,
    isVisible: true,
  },
  {
    id: "fire_planner",
    title: "FIRE Independence Planner",
    subtitle: "Retirement velocity & target capital runway",
    page: "statistics",
    category: "planning",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 2,
    isVisible: true,
  },
  {
    id: "cashflow_outlook",
    title: "Cashflow Outlook",
    subtitle: "Income vs expense pacing & forecast floor",
    page: "statistics",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 3,
    isVisible: true,
  },
  {
    id: "liquidity_horizon",
    title: "Liquidity Horizon",
    subtitle: "Liquid runway & reserve safety buffer",
    page: "statistics",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 4,
    isVisible: true,
  },
  {
    id: "zero_based_envelopes",
    title: "Zero-Based Envelopes",
    subtitle: "Monthly capital allocation across envelopes",
    page: "statistics",
    category: "planning",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 5,
    isVisible: true,
  },
  {
    id: "spending_patterns",
    title: "Spending Patterns",
    subtitle: "Temporal trends & behavioral spending shifts",
    page: "statistics",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full"],
    order: 6,
    isVisible: true,
  },
  {
    id: "spending_density_heatmap",
    title: "Spending Density Heatmap",
    subtitle: "Daily transaction cluster & calendar density",
    page: "statistics",
    category: "telemetry",
    size: "full",
    supportedSizes: ["full"],
    order: 7,
    isVisible: true,
  },
  {
    id: "debt_payoff",
    title: "Debt Payoff Engine",
    subtitle: "Snowball vs Avalanche payoff acceleration",
    page: "statistics",
    category: "planning",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 8,
    isVisible: true,
  },
  {
    id: "what_if_simulator",
    title: "What-If Simulator",
    subtitle: "Income/expense shock scenario modeling",
    page: "statistics",
    category: "planning",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 9,
    isVisible: true,
  },
  {
    id: "personal_financial_model",
    title: "Personal Financial Model",
    subtitle: "Structural actual vs baseline financial trajectory",
    page: "statistics",
    category: "planning",
    size: "full",
    supportedSizes: ["full", "half"],
    order: 10,
    isVisible: true,
  },
];
